In [64]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, BayesianRidge,Lasso
import tensorflow as tf
from keras.layers import Dense
from keras import Sequential
from lazypredict.Supervised import LazyRegressor
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [65]:
df = pd.read_csv('bayut_listings_ready.csv')
df.head()

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
0,0.00,Floor,0.36,0.40,0.00,"Al Khaleej, East Riyadh, Riyadh"
1,0.00,Apartment,0.14,0.20,0.00,"Al Sakb, Madina"
2,0.00,Apartment,0.14,0.20,0.00,"Al Sakb, Madina"
3,0.00,Apartment,0.14,0.20,0.00,"Al Sakb, Madina"
4,0.00,Apartment,0.36,0.40,0.00,"Al Rabwa, North Jeddah, Jeddah"

In [66]:
X = df.drop(columns='Price', axis=1)
y = df['Price']
col = X.drop(columns='Property Type').columns

In [67]:
df.head(1)

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
0,0.00,Floor,0.36,0.40,0.00,"Al Khaleej, East Riyadh, Riyadh"

In [68]:
targetenc = TargetEncoder(smooth='auto')
X[col] = targetenc.fit_transform(X[col],y)

In [69]:
X.head()

  Property Type  Number Of Bedrooms  Number Of Bathrooms  Area  Location
0         Floor                0.00                 0.00  0.00      0.00
1     Apartment                0.00                 0.00  0.00      0.00
2     Apartment                0.00                 0.00  0.00      0.00
3     Apartment                0.00                 0.00  0.00      0.00
4     Apartment                0.00                 0.00  0.00      0.00

In [70]:
X_encoded = pd.get_dummies(X,columns=['Property Type'],dtype=int)
X_encoded.head()

,Number Of Bedrooms,Number Of Bathrooms,Area,Location,Property Type_Apartment,Property Type_Building,Property Type_Floor,Property Type_Residential Building,Property Type_Rest House,Property Type_Villa
0,0.00,0.00,0.00,0.00,0,0,1,0,0,0
1,0.00,0.00,0.00,0.00,1,0,0,0,0,0
2,0.00,0.00,0.00,0.00,1,0,0,0,0,0
3,0.00,0.00,0.00,0.00,1,0,0,0,0,0
4,0.00,0.00,0.00,0.00,1,0,0,0,0,0

In [78]:
x_train,x_test,y_train,y_test = train_test_split(X_encoded,y,test_size=0.2,random_state=100)

In [72]:
model_linear = LinearRegression().fit(x_train,y_train)
model_bay = BayesianRidge().fit(x_train,y_train)
model_lasso = Lasso().fit(x_train,y_train)
print(f'model performance on training data: {model_linear.score(x_train,y_train)} \nmodel performance on testing data: {model_linear.score(x_test,y_test)}')
print(f'model_bay performance on training data: {model_bay.score(x_train,y_train)} \nmodel_bay performance on testing data: {model_bay.score(x_test,y_test)}')
print(f'model_lasso performance on training data: {model_lasso.score(x_train,y_train)} \nmodel_lasso performance on testing data: {model_lasso.score(x_test,y_test)}')

model performance on training data: 0.3928034924854644
model performance on testing data: 0.4977927048115557
model_bay performance on training data: 0.39280129202811687
model_bay performance on testing data: 0.4980159780810145
model_lasso performance on training data: 0.0
model_lasso performance on testing data: -0.00021385254637351636

In [73]:
model = tf.keras.Sequential([Dense(units=25,activation='relu'),
                             Dense(units=15,activation='relu'),
                             Dense(units=1)])
model.compile(loss=tf.keras.losses.MeanSquaredError(
    reduction='sum_over_batch_size',
    name='mean_squared_error'),
    metrics=[tf.keras.metrics.MeanSquaredError()]
)
history = model.fit(
    x_train,
    y_train,
    batch_size=64,
    epochs=100,
    # We pass some validation for
    # monitoring validation loss and metrics
    # at the end of each epoch
   
)

Epoch 1/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 0.0019 - mean_squared_error: 0.0019
Epoch 2/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 6.1983e-05 - mean_squared_error: 6.1983e-05
Epoch 3/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - loss: 5.3575e-05 - mean_squared_error: 5.3575e-05
Epoch 4/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - loss: 5.4298e-05 - mean_squared_error: 5.4298e-05
Epoch 5/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - loss: 4.5912e-05 - mean_squared_error: 4.5912e-05
Epoch 6/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - loss: 4.5809e-05 - mean_squared_error: 4.5809e-05
Epoch 7/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - loss: 4.4955e-05 - mean_squared_error: 4.4955e-05
Epoch 8/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - loss: 5.1129e-05 - mean_squared_error: 5.1129e-05
Epoch 9/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - loss: 6.1939e-05 - mean_squared_error: 6.1939e-05
Epoch 10/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - loss: 5.6399e-05 - mean_squared_error: 5.6399e-05
Epoch 11/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 5.1221e-05 - mean_squared_error: 5.1221e-05
Epoch 12/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 4.1326e-05 - mean_squared_error: 4.1326e-05
Epoch 13/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 4.7154e-05 - mean_squared_error: 4.7154e-05
Epoch 14/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 3.4034e-05 - mean_squared_error: 3.4034e-05
Epoch 15/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 3.3879e-05 - mean_squared_error: 3.3879e-05
Epoch 16/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 4.0690e-05 - mean_squared_error: 4.0690e-05
Epoch 17/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 3.6707e-05 - mean_squared_error: 3.6707e-05
Epoch 18/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - loss: 3.1260e-05 - mean_squared_error: 3.1260e-05
Epoch 19/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 3.9094e-05 - mean_squared_error: 3.9094e-05
Epoch 20/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 4.2794e-05 - mean_squared_error: 4.2794e-05
Epoch 21/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 3.5239e-05 - mean_squared_error: 3.5239e-05
Epoch 22/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 3.1035e-05 - mean_squared_error: 3.1035e-05
Epoch 23/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 3.3932e-05 - mean_squared_error: 3.3932e-05
Epoch 24/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - loss: 3.7008e-05 - mean_squared_error: 3.7008e-05
Epoch 25/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - loss: 2.8735e-05 - mean_squared_error: 2.8735e-05
Epoch 26/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 2.5174e-05 - mean_squared_error: 2.5174e-05
Epoch 27/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 2.8215e-05 - mean_squared_error: 2.8215e-05
Epoch 28/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 3.3275e-05 - mean_squared_error: 3.3275e-05
Epoch 29/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 2.4890e-05 - mean_squared_error: 2.4890e-05
Epoch 30/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 2.7328e-05 - mean_squared_error: 2.7328e-05
Epoch 31/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 3.2494e-05 - mean_squared_error: 3.2494e-05
Epoch 32/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 2.4756e-05 - mean_squared_error: 2.4756e-05
Epoch 33/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 2.6300e-05 - mean_squared_error: 2.6300e-05
Epoch 34/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - loss: 3.3919e-05 - mean_squared_error: 3.3919e-05
Epoch 35/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 2.6429e-05 - mean_squared_error: 2.6429e-05
Epoch 36/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - loss: 2.1994e-05 - mean_squared_error: 2.1994e-05
Epoch 37/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 2.4024e-05 - mean_squared_error: 2.4024e-05
Epoch 38/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 2.2212e-05 - mean_squared_error: 2.2212e-05
Epoch 39/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 2.3781e-05 - mean_squared_error: 2.3781e-05
Epoch 40/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 2.0813e-05 - mean_squared_error: 2.0813e-05
Epoch 41/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - loss: 2.4259e-05 - mean_squared_error: 2.4259e-05
Epoch 42/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - loss: 2.2450e-05 - mean_squared_error: 2.2450e-05
Epoch 43/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 1.7267e-05 - mean_squared_error: 1.7267e-05
Epoch 44/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 1.8727e-05 - mean_squared_error: 1.8727e-05
Epoch 45/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 2.1938e-05 - mean_squared_error: 2.1938e-05
Epoch 46/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - loss: 2.1399e-05 - mean_squared_error: 2.1399e-05
Epoch 47/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - loss: 1.9384e-05 - mean_squared_error: 1.9384e-05
Epoch 48/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - loss: 2.1329e-05 - mean_squared_error: 2.1329e-05
Epoch 49/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 3.1642e-05 - mean_squared_error: 3.1642e-05
Epoch 50/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - loss: 2.0604e-05 - mean_squared_error: 2.0604e-05
Epoch 51/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 1.8669e-05 - mean_squared_error: 1.8669e-05
Epoch 52/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 1.7216e-05 - mean_squared_error: 1.7216e-05
Epoch 53/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 1.9063e-05 - mean_squared_error: 1.9063e-05
Epoch 54/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 1.9105e-05 - mean_squared_error: 1.9105e-05
Epoch 55/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 1.4538e-05 - mean_squared_error: 1.4538e-05
Epoch 56/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 2.0318e-05 - mean_squared_error: 2.0318e-05
Epoch 57/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 1.7767e-05 - mean_squared_error: 1.7767e-05
Epoch 58/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 1.4411e-05 - mean_squared_error: 1.4411e-05
Epoch 59/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 2.2954e-05 - mean_squared_error: 2.2954e-05
Epoch 60/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - loss: 2.5507e-05 - mean_squared_error: 2.5507e-05
Epoch 61/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - loss: 1.7134e-05 - mean_squared_error: 1.7134e-05
Epoch 62/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - loss: 1.8662e-05 - mean_squared_error: 1.8662e-05
Epoch 63/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 2.0980e-05 - mean_squared_error: 2.0980e-05
Epoch 64/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 2.5305e-05 - mean_squared_error: 2.5305e-05
Epoch 65/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 1.7779e-05 - mean_squared_error: 1.7779e-05
Epoch 66/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 1.7612e-05 - mean_squared_error: 1.7612e-05
Epoch 67/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - loss: 1.8546e-05 - mean_squared_error: 1.8546e-05
Epoch 68/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - loss: 1.9257e-05 - mean_squared_error: 1.9257e-05
Epoch 69/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - loss: 2.1912e-05 - mean_squared_error: 2.1912e-05
Epoch 70/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - loss: 1.8894e-05 - mean_squared_error: 1.8894e-05
Epoch 71/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - loss: 2.1337e-05 - mean_squared_error: 2.1337e-05
Epoch 72/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - loss: 1.4574e-05 - mean_squared_error: 1.4574e-05
Epoch 73/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - loss: 1.7802e-05 - mean_squared_error: 1.7802e-05
Epoch 74/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - loss: 2.7408e-05 - mean_squared_error: 2.7408e-05
Epoch 75/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - loss: 1.5166e-05 - mean_squared_error: 1.5166e-05
Epoch 76/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - loss: 1.3228e-05 - mean_squared_error: 1.3228e-05
Epoch 77/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - loss: 1.3695e-05 - mean_squared_error: 1.3695e-05
Epoch 78/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - loss: 1.8858e-05 - mean_squared_error: 1.8858e-05
Epoch 79/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - loss: 1.7637e-05 - mean_squared_error: 1.7637e-05
Epoch 80/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 1.4279e-05 - mean_squared_error: 1.4279e-05
Epoch 81/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 1.3730e-05 - mean_squared_error: 1.3730e-05
Epoch 82/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 1.8676e-05 - mean_squared_error: 1.8676e-05
Epoch 83/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - loss: 1.2901e-05 - mean_squared_error: 1.2901e-05
Epoch 84/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - loss: 1.9423e-05 - mean_squared_error: 1.9423e-05
Epoch 85/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 1.2911e-05 - mean_squared_error: 1.2911e-05
Epoch 86/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 1.5238e-05 - mean_squared_error: 1.5238e-05
Epoch 87/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 1.3548e-05 - mean_squared_error: 1.3548e-05
Epoch 88/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - loss: 1.3717e-05 - mean_squared_error: 1.3717e-05
Epoch 89/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 1.8446e-05 - mean_squared_error: 1.8446e-05
Epoch 90/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 1.8744e-05 - mean_squared_error: 1.8744e-05
Epoch 91/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - loss: 1.8989e-05 - mean_squared_error: 1.8989e-05
Epoch 92/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 1.1617e-05 - mean_squared_error: 1.1617e-05
Epoch 93/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 1.2120e-05 - mean_squared_error: 1.2120e-05
Epoch 94/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 1.4176e-05 - mean_squared_error: 1.4176e-05
Epoch 95/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 2.1340e-05 - mean_squared_error: 2.1340e-05
Epoch 96/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - loss: 1.6213e-05 - mean_squared_error: 1.6213e-05
Epoch 97/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 1.1827e-05 - mean_squared_error: 1.1827e-05
Epoch 98/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - loss: 1.7112e-05 - mean_squared_error: 1.7112e-05
Epoch 99/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - loss: 1.2029e-05 - mean_squared_error: 1.2029e-05
Epoch 100/100
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - loss: 1.4513e-05 - mean_squared_error: 1.4513e-05

In [74]:
print(history.history) # this will print a dictionary object, now you need to grab the metrics / score you're looking for

{'loss': [0.00044979789527133107, 5.382890230976045e-05, 5.0297003326704726e-05, 4.897643157164566e-05, 4.7367429942823946e-05, 4.690714195021428e-05, 4.5433927880367264e-05, 4.922290099784732e-05, 5.192234311834909e-05, 4.936351251672022e-05, 4.6938886953284964e-05, 4.383761915960349e-05, 4.198965325485915e-05, 3.810493944911286e-05, 3.814954834524542e-05, 3.6270539567340165e-05, 3.6463003198150545e-05, 3.417503830860369e-05, 3.6631361581385136e-05, 3.562368874554522e-05, 3.491989627946168e-05, 3.3719879866112024e-05, 3.329255559947342e-05, 3.275039853178896e-05, 3.1171806767815724e-05, 3.0375784263014793e-05, 2.9989369068061933e-05, 3.0128963771858253e-05, 2.8310732886893675e-05, 2.8367319828248583e-05, 2.780848262773361e-05, 2.6737665393739007e-05, 2.677953671081923e-05, 2.6148209144594148e-05, 2.6168218028033152e-05, 2.4752438548603095e-05, 2.4676350221852772e-05, 2.464733915985562e-05, 2.4521199520677328e-05, 2.3737209630780853e-05, 2.3245549527928233e-05, 2.3102735212887637e-05, 2.3563159629702568e-05, 2.262328598590102e-05, 2.1443809600896202e-05, 2.1523341274587438e-05, 2.1337007638067007e-05, 2.178054091928061e-05, 2.084291736537125e-05, 2.105103703797795e-05, 2.0412999219843186e-05, 2.0570732885971665e-05, 2.035853140114341e-05, 1.956443884409964e-05, 1.9084092855337076e-05, 1.9626973880804144e-05, 1.9273296857136302e-05, 1.990583405131474e-05, 1.8623903088155203e-05, 1.9046961824642494e-05, 1.9198649169993587e-05, 1.870383130153641e-05, 1.8712447854341008e-05, 1.8080872905557044e-05, 1.8481168808648363e-05, 1.851100205385592e-05, 1.77248857653467e-05, 1.8364773495704867e-05, 1.8170647308579646e-05, 1.8136948710889556e-05, 1.8067114069708623e-05, 1.783178777259309e-05, 1.7600499631953426e-05, 1.7378381016897038e-05, 1.7378511984134093e-05, 1.7557384126121178e-05, 1.7577804101165384e-05, 1.747843089106027e-05, 1.7229254808626138e-05, 1.74246852111537e-05, 1.6941374269663356e-05, 1.6993575627566315e-05, 1.678907938185148e-05, 1.705295107967686e-05, 1.7044530977727845e-05, 1.686774703557603e-05, 1.6843408957356587e-05, 1.681193316471763e-05, 1.6599055015831254e-05, 1.6631962353130803e-05, 1.6380268789362162e-05, 1.62570158863673e-05, 1.6468689864268526e-05, 1.6388057701988146e-05, 1.6486064851051196e-05, 1.5959161828504875e-05, 1.644721305638086e-05, 1.6066198440967128e-05, 1.607479134690948e-05, 1.62191572599113e-05], 'mean_squared_error': [0.00044979789527133107, 5.382890230976045e-05, 5.0297003326704726e-05, 4.897643157164566e-05, 4.7367429942823946e-05, 4.690714195021428e-05, 4.5433927880367264e-05, 4.922290099784732e-05, 5.192234311834909e-05, 4.936351251672022e-05, 4.6938886953284964e-05, 4.383761915960349e-05, 4.198965325485915e-05, 3.810493944911286e-05, 3.814954834524542e-05, 3.6270539567340165e-05, 3.6463003198150545e-05, 3.417503830860369e-05, 3.6631361581385136e-05, 3.562368874554522e-05, 3.491989627946168e-05, 3.3719879866112024e-05, 3.329255559947342e-05, 3.275039853178896e-05, 3.1171806767815724e-05, 3.0375784263014793e-05, 2.9989369068061933e-05, 3.0128963771858253e-05, 2.8310732886893675e-05, 2.8367319828248583e-05, 2.780848262773361e-05, 2.6737665393739007e-05, 2.677953671081923e-05, 2.6148209144594148e-05, 2.6168218028033152e-05, 2.4752438548603095e-05, 2.4676350221852772e-05, 2.464733915985562e-05, 2.4521199520677328e-05, 2.3737209630780853e-05, 2.3245549527928233e-05, 2.3102735212887637e-05, 2.3563159629702568e-05, 2.262328598590102e-05, 2.1443809600896202e-05, 2.1523341274587438e-05, 2.1337007638067007e-05, 2.178054091928061e-05, 2.084291736537125e-05, 2.105103703797795e-05, 2.0412999219843186e-05, 2.0570732885971665e-05, 2.035853140114341e-05, 1.956443884409964e-05, 1.9084092855337076e-05, 1.9626973880804144e-05, 1.9273296857136302e-05, 1.990583405131474e-05, 1.8623903088155203e-05, 1.9046961824642494e-05, 1.9198649169993587e-05, 1.870383130153641e-05, 1.8712447854341008e-05, 1.8080872905557044e-05, 1.8481168808648363e-05, 1.851100205385592e-05, 1.77248857653467e-05, 1.8364773495704867e-05, 1.8170647308579646e-05, 1.8136948710889556e-05, 1.8067114069708623e-05, 1.783178777259309e-05, 1.7600499631953426e-05, 1.7378381016897038e-05, 1.7378511984134093e-05, 1.7557384126121178e-05, 1.7577804101165384e-05, 1.747843089106027e-05, 1.7229254808626138e-05, 1.74246852111537e-05, 1.6941374269663356e-05, 1.6993575627566315e-05, 1.678907938185148e-05, 1.705295107967686e-05, 1.7044530977727845e-05, 1.686774703557603e-05, 1.6843408957356587e-05, 1.681193316471763e-05, 1.6599055015831254e-05, 1.6631962353130803e-05, 1.6380268789362162e-05, 1.62570158863673e-05, 1.6468689864268526e-05, 1.6388057701988146e-05, 1.6486064851051196e-05, 1.5959161828504875e-05, 1.644721305638086e-05, 1.6066198440967128e-05, 1.607479134690948e-05, 1.62191572599113e-05]}

In [75]:
loss, accuracy = model.evaluate(x_train, x_train, batch_size=1000)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 0.0991 - mean_squared_error: 0.0991
Test Loss: 0.0991
Test Accuracy: 0.0991

In [79]:
reg = LazyRegressor(verbose=0,ignore_warnings=False, custom_metric=None )
models,predictions = reg.fit(x_train, x_test, y_train, y_test)

100%|██████████| 42/42 [00:34<00:00,  1.23it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000179 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 640
[LightGBM] [Info] Number of data points in the train set: 9835, number of used features: 10
[LightGBM] [Info] Start training from score 0.003250

In [80]:
models.head()

                               Adjusted R-Squared  R-Squared  RMSE  Time Taken
Model
LGBMRegressor                                0.51       0.51  0.00        0.04
HistGradientBoostingRegressor                0.50       0.50  0.00        0.14
GradientBoostingRegressor                    0.50       0.50  0.00        0.46
SGDRegressor                                 0.48       0.48  0.00        0.01
KNeighborsRegressor                          0.47       0.48  0.00        0.10

In [81]:
predictions.head()

                               Adjusted R-Squared  R-Squared  RMSE  Time Taken
Model
LGBMRegressor                                0.51       0.51  0.00        0.04
HistGradientBoostingRegressor                0.50       0.50  0.00        0.14
GradientBoostingRegressor                    0.50       0.50  0.00        0.46
SGDRegressor                                 0.48       0.48  0.00        0.01
KNeighborsRegressor                          0.47       0.48  0.00        0.10

In [84]:
print('oi')

oi

In [85]:
print('oi')
print('oi')

oi
oi

In [ ]:
asd