In [1036]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, BayesianRidge,Lasso

In [1037]:
df = pd.read_csv('bayut_listings_ready.csv')
df.head()

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
0,0.002892,Floor,0.357143,0.4,0.003385,"Al Khaleej, East Riyadh, Riyadh"
1,0.001155,Apartment,0.142857,0.2,0.000960,"Al Sakb, Madina"
2,0.001155,Apartment,0.142857,0.2,0.000960,"Al Sakb, Madina"
3,0.001155,Apartment,0.142857,0.2,0.000960,"Al Sakb, Madina"
4,0.002200,Apartment,0.357143,0.4,0.001423,"Al Rabwa, North Jeddah, Jeddah"

In [1038]:
X = df.drop(columns='Price', axis=1)
y = df['Price']
col = X.drop(columns='Property Type').columns

In [1039]:
df.head(1)

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
0,0.002892,Floor,0.357143,0.4,0.003385,"Al Khaleej, East Riyadh, Riyadh"

In [1040]:
targetenc = TargetEncoder(smooth='auto')
X[col] = targetenc.fit_transform(X[col],y)

In [1041]:
X.head()

  Property Type  Number Of Bedrooms  Number Of Bathrooms      Area  Location
0         Floor            0.004708             0.004950  0.004079  0.003691
1     Apartment            0.002109             0.001998  0.001593  0.001688
2     Apartment            0.002151             0.001983  0.001562  0.001435
3     Apartment            0.002122             0.001976  0.001604  0.001501
4     Apartment            0.004722             0.004859  0.002544  0.002253

In [1042]:
X_encoded = pd.get_dummies(X,columns=['Property Type'],dtype=int)
X_encoded.head()

,Number Of Bedrooms,Number Of Bathrooms,Area,Location,Property Type_Apartment,Property Type_Building,Property Type_Floor,Property Type_Residential Building,Property Type_Rest House,Property Type_Villa
0,0.004708,0.004950,0.004079,0.003691,0,0,1,0,0,0
1,0.002109,0.001998,0.001593,0.001688,1,0,0,0,0,0
2,0.002151,0.001983,0.001562,0.001435,1,0,0,0,0,0
3,0.002122,0.001976,0.001604,0.001501,1,0,0,0,0,0
4,0.004722,0.004859,0.002544,0.002253,1,0,0,0,0,0

In [1043]:
x_train,x_test,y_train,y_test = train_test_split(X_encoded,y,test_size=0.2)

In [1044]:
model_linear = LinearRegression().fit(x_train,y_train)
model_bay = BayesianRidge().fit(x_train,y_train)
model_lasso = Lasso().fit(x_train,y_train)
print(f'model performance on training data: {model_linear.score(x_train,y_train)} \nmodel performance on testing data: {model_linear.score(x_test,y_test)}')
print(f'model performance on training data: {model_bay.score(x_train,y_train)} \nmodel performance on testing data: {model_bay.score(x_test,y_test)}')
print(f'model performance on training data: {model_lasso.score(x_train,y_train)} \nmodel performance on testing data: {model_lasso.score(x_test,y_test)}')

model performance on training data: 0.3912510851822849
model performance on testing data: 0.4585929326810083
model performance on training data: 0.3912488106971097
model performance on testing data: 0.4584989149027059
model performance on training data: 0.0
model performance on testing data: -3.542401465828071e-05