In [2]:
import pandas as pd 
import numpy as np
import re

In [3]:
df = pd.read_csv('raw_data/propertyfinder_listings.csv')
numeric_cols = ['Price', 'Number Of Bedrooms', 'Number Of Bathrooms', 'Area']

In [4]:
df.head()

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
0,"5,000,000 SAR",Rest House,4,4,"1,420 sqm","شاطئ نصف القمر, Ad Dammam, Eastern"
1,"6,000,000 SAR",Villa,7+,7+,500 sqm,"Al Wadi, Riyadh, Ar Riyadh"
2,"1,650,000 SAR",Apartment,3,4,144 sqm,"An Narjis, Riyadh, Ar Riyadh"
3,"2,400,000 SAR",Whole Building,7+,7+,423 sqm,"Al Faisaliyah, Jeddah, Makkah Al Mukarramah"
4,"2,500,000 SAR",Villa,7+,2,395 sqm,"Al Muhammadiyah, Jeddah, Makkah Al Mukarramah"

In [14]:
df.describe()

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
count,3347,3347,3347,3347,3347,3347
unique,281,6,17,8,454,397
top,"650,000 SAR",Apartment,5,3,300 sqm,"Al Janadriyah, Riyadh, Ar Riyadh"
freq,134,1874,919,1181,77,136

In [17]:
df

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
0,"5,000,000 SAR",Rest House,4,4,"1,420 sqm","شاطئ نصف القمر, Ad Dammam, Eastern"
1,"6,000,000 SAR",Villa,7+,7+,500 sqm,"Al Wadi, Riyadh, Ar Riyadh"
2,"1,650,000 SAR",Apartment,3,4,144 sqm,"An Narjis, Riyadh, Ar Riyadh"
3,"2,400,000 SAR",Whole Building,7+,7+,423 sqm,"Al Faisaliyah, Jeddah, Makkah Al Mukarramah"
4,"2,500,000 SAR",Villa,7+,2,395 sqm,"Al Muhammadiyah, Jeddah, Makkah Al Mukarramah"
...,...,...,...,...,...,...
3342,"540,000 SAR",Apartment,6,3,130 sqm,"Ar Rayaan, Jeddah, Makkah Al Mukarramah"
3343,"600,000 SAR",Apartment,5,4,203 sqm,"Al Yaqoot, Abha, Asir"
3344,"1,030,000 SAR",Apartment,6,4,206 sqm,"As Salamah, Jeddah, Makkah Al Mukarramah"
3345,"540,000 SAR",Apartment,6,3,130 sqm,"Ar Rayaan, Jeddah, Makkah Al Mukarramah"
3346,"400,000 SAR",Apartment,5,3,120 sqm,"شهار, امارة منطقة مكة المكرمة - الطائف, Makkah..."

In [34]:
df2 = df.dropna()
df2 = df2[~df2['Property Type'].str.contains(r'\d')]
df2[numeric_cols] = df2[numeric_cols].map(lambda x: re.sub(r'\D', '', str(x)))

In [35]:
df2

,Price,Property Type,Number Of Bedrooms,Number Of Bathrooms,Area,Location
0,5000000,Rest House,4,4,1420,"شاطئ نصف القمر, Ad Dammam, Eastern"
1,6000000,Villa,7,7,500,"Al Wadi, Riyadh, Ar Riyadh"
2,1650000,Apartment,3,4,144,"An Narjis, Riyadh, Ar Riyadh"
3,2400000,Whole Building,7,7,423,"Al Faisaliyah, Jeddah, Makkah Al Mukarramah"
4,2500000,Villa,7,2,395,"Al Muhammadiyah, Jeddah, Makkah Al Mukarramah"
...,...,...,...,...,...,...
3342,540000,Apartment,6,3,130,"Ar Rayaan, Jeddah, Makkah Al Mukarramah"
3343,600000,Apartment,5,4,203,"Al Yaqoot, Abha, Asir"
3344,1030000,Apartment,6,4,206,"As Salamah, Jeddah, Makkah Al Mukarramah"
3345,540000,Apartment,6,3,130,"Ar Rayaan, Jeddah, Makkah Al Mukarramah"
3346,400000,Apartment,5,3,120,"شهار, امارة منطقة مكة المكرمة - الطائف, Makkah..."

In [37]:
df2['Property Type'].value_counts()

Property Type
Apartment         1874
Villa              968
Full Floor         473
Whole Building      27
Rest House           4
Compound             1
Name: count, dtype: int64